
?document: element*

?element: header
        | paragraph
        | command_block
        | list

// --- Headers ---
header: h1 | h2 | h3
h1: HASH TEXT NEWLINE?
h2: HASH HASH TEXT NEWLINE?
h3: HASH HASH HASH TEXT NEWLINE?

// --- Paragraphs & Sentences ---
paragraph: sentence+
sentence: text+ (DOT | NEWLINE)?

// --- Lists ---
list: item+
item: STAR text+ NEWLINE?

// --- Command blocks ---
command_block: BANG command_body BANG NEWLINE?
command_body: (TEXT | NEWLINE)+


// --- Tokens ---
HASH: "#"
STAR: "*"
BANG: "!"
DOT: "."
NEWLINE: /\n+/

// --- Text types ---



TEXT: /[a-zA-Z0-9,.?^_=()+\- $\\{}<>[\]-]+/



COMMAND_TEXT: /(\\[^!\n]+|[^!])+/ 
text: TEXT

