
?document: element*

?element: header
        | paragraph
        | command_block
        | list

// --- Headers ---
header: h1 | h2 | h3
h1: HASH TEXT NEWLINE
h2: HASH HASH TEXT NEWLINE
h3: HASH HASH HASH TEXT NEWLINE

// --- Paragraphs & Sentences ---
paragraph: sentence+
sentence: text_inline+ (DOT | NEWLINE)

list: item+
item: STAR (text_inline)+ NEWLINE?

// --- Inline commands ---
inline_command: DOLLAR COMMAND_TEXT DOLLAR
command_block: BANG command_body BANG NEWLINE?
command_body: (COMMAND_TEXT | NEWLINE)+

// --- Tokens ---
HASH: "#"
STAR: "*"
DOLLAR: "$"
BANG: "!"
DOT: "."
NEWLINE: /\n+/

// --- Text types ---


TEXT: /[a-zA-Z0-9,.?^_=()+\- ]+/

COMMAND_TEXT: /(\\[^$!\n]+|[^$!])+/ 
text_inline: TEXT | inline_command

